<a href="https://colab.research.google.com/github/roshank1605A04/MNIST-Dataset/blob/master/mnist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Installing the Libraries**

In [0]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
#import seaborn as sns

**Importing the Dataset**

In [0]:
train = pd.read_csv('drive/My Drive/Projects/mnist text/mnist_train.csv')
test = pd.read_csv('drive/My Drive/Projects/mnist text/mnist_test.csv')

print(train.shape)
print(test.shape)

train.head()

(60000, 785)
(10000, 785)


label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...    28x19  28x20  \
0      5    0    0    0    0    0    0    0    0    0  ...        0      0   
1      0    0    0    0    0    0    0    0    0    0  ...        0      0   
2      4    0    0    0    0    0    0    0    0    0  ...        0      0   
3      1    0    0    0    0    0    0    0    0    0  ...        0      0   
4      9    0    0    0    0    0    0    0    0    0  ...        0      0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [0]:
test.head()

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...    28x19  28x20  \
0      7    0    0    0    0    0    0    0    0    0  ...        0      0   
1      2    0    0    0    0    0    0    0    0    0  ...        0      0   
2      1    0    0    0    0    0    0    0    0    0  ...        0      0   
3      0    0    0    0    0    0    0    0    0    0  ...        0      0   
4      4    0    0    0    0    0    0    0    0    0  ...        0      0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0  

[5 rows x 785 columns]

**Data Preprocessing**

In [0]:
# It has 10 digits ranging from 0-9

train.iloc[:,0].value_counts()

1    6742
7    6265
3    6131
2    5958
9    5949
0    5923
6    5918
8    5851
4    5842
5    5421
Name: label, dtype: int64

In [0]:
# splitting the data into dependent and independent variables

train_x = train.iloc[:,1:785]
train_y = train.iloc[:,0]

test_x = test.iloc[:,1:785]
test_y = test.iloc[:,0]

print(train_x.shape)
print(train_y.shape)

print(test_x.shape)
print(test_y.shape)


(60000, 784)
(60000,)
(10000, 784)
(10000,)


In [0]:
# splitting the dataset into training and testing set

from sklearn.cross_validation import train_test_split

x_train, x_cv, y_train, y_cv = train_test_split(train_x, train_y, test_size = 0.25, random_state = 35)

print(x_train.shape)
print(x_cv.shape)
print(y_train.shape)
print(y_cv.shape)

(45000, 784)
(15000, 784)
(45000,)
(15000,)


In [0]:
# reshaping them as matrix

x_train = np.asmatrix(x_train).reshape(45000, 784)
x_cv = np.asmatrix(x_cv).reshape(15000, 784)

test_x = np.asmatrix(test_x).reshape(10000, 784)

In [0]:
# feature normalization

x_train = x_train.astype('float32')
x_cv = x_cv.astype('float32')

test_x = test_x.astype('float32')

x_train = x_train/255
x_cv = x_cv/255
test_x = test_x/255

In [0]:
# converting the labels into one hot encoding

# immporting keras 
import keras

digits = 10
y_train = keras.utils.to_categorical(y_train, digits)
y_cv = keras.utils.to_categorical(y_cv, digits)



In [0]:
# viewing the labels after one hot encoding

print(y_train[0])  #7
print(y_train[3])  #2
print(y_train[4])  #4

[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


**Modelling**

**Artificial Neural Networks**

In [0]:
import keras 
from keras.layers import Dense 
from keras.models import Sequential
from keras import optimizers

In [0]:
# creating the model
model = Sequential()

# first hidden layer
model.add(Dense(output_dim = 400, init = 'uniform', activation = 'relu', input_dim = 784))

# second hidden layer
model.add(Dense(output_dim = 300, init = 'uniform', activation = 'relu'))

# third hidden layer
model.add(Dense(output_dim = 300, init = 'uniform', activation = 'relu'))

# fourth hidden layer
model.add(Dense(output_dim = 300, init = 'uniform', activation = 'relu'))

# fifth hidden layer
model.add(Dense(output_dim = 100, init = 'uniform', activation = 'relu'))

# output layer
# output_dim = no. of digits
# softmax activation function is used for multiple outputs
model.add(Dense(output_dim = 10, init = 'uniform', activation = 'softmax'))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=784, units=400, kernel_initializer="uniform")`
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=300, kernel_initializer="uniform")`
  import sys
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=300, kernel_initializer="uniform")`
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:13: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=300, kernel_initializer="uniform")`
  del sys.path[0]
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:16: UserWarning: Update your `Dense` 

In [0]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 400)               314000    
_________________________________________________________________
dense_2 (Dense)              (None, 300)               120300    
_________________________________________________________________
dense_3 (Dense)              (None, 300)               90300     
_________________________________________________________________
dense_4 (Dense)              (None, 300)               90300     
_________________________________________________________________
dense_5 (Dense)              (None, 100)               30100     
_________________________________________________________________
dense_6 (Dense)              (None, 10)                1010      
Total params: 646,010
Trainable params: 646,010
Non-trainable params: 0
_________________________________________________________________


**Using Stochastic gradient descent as our Optimizer**

In [0]:
# setting the learning rate
learning_rate = 0.01
sgd = optimizers.SGD(lr = learning_rate)


# compiling the model
# using the plain vanilla stochastic gradient descent as our optimizing technique
# using categorical cross entropy for multiple outputs
model.compile(optimizer = 'sgd', loss = 'categorical_crossentropy', metrics = ['accuracy'])

# feeding the training data to the model
model.fit(x_train, y_train, batch_size = 100, epochs = 60, verbose = 2, validation_data = (x_cv, y_cv))

Train on 45000 samples, validate on 15000 samples
Epoch 1/100
 - 7s - loss: 2.2999 - acc: 0.1122 - val_loss: 2.2994 - val_acc: 0.1129
Epoch 2/100
 - 7s - loss: 2.2992 - acc: 0.1122 - val_loss: 2.2986 - val_acc: 0.1129
Epoch 3/100
 - 7s - loss: 2.2982 - acc: 0.1122 - val_loss: 2.2974 - val_acc: 0.1129
Epoch 4/100
 - 7s - loss: 2.2966 - acc: 0.1122 - val_loss: 2.2952 - val_acc: 0.1129
Epoch 5/100
 - 7s - loss: 2.2934 - acc: 0.1125 - val_loss: 2.2906 - val_acc: 0.1170
Epoch 6/100
 - 7s - loss: 2.2852 - acc: 0.1694 - val_loss: 2.2761 - val_acc: 0.2090
Epoch 7/100
 - 7s - loss: 2.2451 - acc: 0.2142 - val_loss: 2.1825 - val_acc: 0.2109
Epoch 8/100
 - 7s - loss: 2.0459 - acc: 0.2308 - val_loss: 1.8748 - val_acc: 0.2833
Epoch 9/100
 - 7s - loss: 1.6617 - acc: 0.3657 - val_loss: 1.4902 - val_acc: 0.4318
Epoch 10/100
 - 7s - loss: 1.4199 - acc: 0.4646 - val_loss: 1.3250 - val_acc: 0.5090
Epoch 11/100
 - 7s - loss: 1.1910 - acc: 0.5924 - val_loss: 0.9512 - val_acc: 0.7245
Epoch 12/100
 - 7s - los

**Using Adam Optimizer**

In [0]:
# creating the model
model = Sequential()

# first hidden layer
model.add(Dense(output_dim = 400, init = 'uniform', activation = 'relu', input_dim = 784))

# second hidden layer
model.add(Dense(output_dim = 300, init = 'uniform', activation = 'relu'))

# third hidden layer
model.add(Dense(output_dim = 300, init = 'uniform', activation = 'relu'))

# fourth hidden layer
model.add(Dense(output_dim = 300, init = 'uniform', activation = 'relu'))

# fifth hidden layer
model.add(Dense(output_dim = 100, init = 'uniform', activation = 'relu'))

# output layer
# output_dim = no. of digits
# softmax activation function is used for multiple outputs
model.add(Dense(output_dim = 10, init = 'uniform', activation = 'softmax'))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=784, units=400, kernel_initializer="uniform")`
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=300, kernel_initializer="uniform")`
  import sys
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=300, kernel_initializer="uniform")`
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:13: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=300, kernel_initializer="uniform")`
  del sys.path[0]
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:16: UserWarning: Update your `Dense` 

In [0]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 400)               314000    
_________________________________________________________________
dense_8 (Dense)              (None, 300)               120300    
_________________________________________________________________
dense_9 (Dense)              (None, 300)               90300     
_________________________________________________________________
dense_10 (Dense)             (None, 300)               90300     
_________________________________________________________________
dense_11 (Dense)             (None, 100)               30100     
_________________________________________________________________
dense_12 (Dense)             (None, 10)                1010      
Total params: 646,010
Trainable params: 646,010
Non-trainable params: 0
_________________________________________________________________


In [0]:
# setting the learning rate
learning_rate = 0.01
adam = optimizers.Adam(lr = learning_rate)


# compiling the model
# using the plain vanilla stochastic gradient descent as our optimizing technique
# using categorical cross entropy for multiple outputs
model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

# feeding the training data to the model
model.fit(x_train, y_train, batch_size = 100, epochs = 20, verbose = 2, validation_data = (x_cv, y_cv))

Train on 45000 samples, validate on 15000 samples
Epoch 1/20
 - 9s - loss: 0.4441 - acc: 0.8571 - val_loss: 0.1924 - val_acc: 0.9418
Epoch 2/20
 - 9s - loss: 0.1457 - acc: 0.9574 - val_loss: 0.1520 - val_acc: 0.9557
Epoch 3/20
 - 9s - loss: 0.0949 - acc: 0.9720 - val_loss: 0.1151 - val_acc: 0.9679
Epoch 4/20
 - 9s - loss: 0.0696 - acc: 0.9799 - val_loss: 0.1102 - val_acc: 0.9685
Epoch 5/20
 - 9s - loss: 0.0549 - acc: 0.9831 - val_loss: 0.1200 - val_acc: 0.9685
Epoch 6/20
 - 9s - loss: 0.0452 - acc: 0.9868 - val_loss: 0.1269 - val_acc: 0.9679
Epoch 7/20
 - 9s - loss: 0.0413 - acc: 0.9877 - val_loss: 0.1094 - val_acc: 0.9722
Epoch 8/20
 - 9s - loss: 0.0338 - acc: 0.9901 - val_loss: 0.1130 - val_acc: 0.9719
Epoch 9/20
 - 8s - loss: 0.0291 - acc: 0.9917 - val_loss: 0.1220 - val_acc: 0.9715
Epoch 10/20
 - 9s - loss: 0.0290 - acc: 0.9917 - val_loss: 0.1236 - val_acc: 0.9720
Epoch 11/20
 - 9s - loss: 0.0228 - acc: 0.9931 - val_loss: 0.1115 - val_acc: 0.9737
Epoch 12/20
 - 9s - loss: 0.0200 - 

**Multi Layer Perceptron**

In [0]:
from sklearn.neural_network import MLPClassifier

# creating the model
model = MLPClassifier()

# feeding the training set to the modeel
model.fit(x_train, y_train)

# predicting the results for test set
y_pred = model.predict(test_x)

# calculating the accuracies
print("Training accuracy :", model.score(x_train, y_train))
print("Testing accuracy :", model.score(x_cv, y_cv))


Training accuracy : 1.0
Testing accuracy : 0.9518


**Random Forest Classifier**

In [0]:
from sklearn.ensemble import RandomForestClassifier

# creating model
model = RandomForestClassifier()

# feeding the training data into the model
model.fit(x_train, y_train)

# calculating the accuracy
print("Training accuracy :", model.score(x_train, y_train))
print("Testing accuracy :", model.score(x_cv, y_cv))

Training accuracy : 0.9911777777777778
Testing accuracy : 0.8478666666666667
